### ISSUE TITLE
Possible to increase number of significant digits options in app for Uncertainty budget?

### ISSUE THREAD

**Issue by tin-** [SandiaPSL/UncertaintyCalc#6]
Hello,

I've been testing app (Windows version, v1.5.5) for uncertainty budgets math using resistance standards and DCC bridges, with datasets deviations and uncertainty <0.2ppm. It works great for main math, but there a limitation in report generator to only maximum 6 significant digits. Perhaps it's possible to consider increasing that number to 8 in future releases? Thanks!

**Comment by cdelker** [comment]
Done in version 1.5.6 - up to 8 significant figures can be shown.
